package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mp-pinheiro/substrate/internal/config"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "generate-registry: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findRoot()
	if err != nil {
		return fmt.Errorf("find repo root: %w", err)
	}

	sourceDirs, err := checkSourceDirs(root)
	if err != nil {
		return err
	}

	digests := make(map[string]string)
	var keys []string

	collect := func(dir string) error {
		entries, err := os.ReadDir(dir)
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return fmt.Errorf("read %s: %w", dir, err)
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".sh") {
				continue
			}
			h, err := sha256File(filepath.Join(dir, e.Name()))
			if err != nil {
				return fmt.Errorf("hash %s: %w", e.Name(), err)
			}
			if _, ok := digests[e.Name()]; !ok {
				keys = append(keys, e.Name())
			}
			digests[e.Name()] = h
		}
		return nil
	}

	for _, dir := range sourceDirs {
		if err := collect(dir); err != nil {
			return err
		}
	}
	sort.Strings(keys)

	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by generate-registry; DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "package gate")
	fmt.Fprintln(&source)
	fmt.Fprintln(&source, "var RegistryDigests = map[string]string{")
	for _, k := range keys {
		fmt.Fprintf(&source, "\t%q: %q,\n", k, digests[k])
	}
	fmt.Fprintln(&source, "}")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format generated registry: %w", err)
	}
	if _, err := os.Stdout.Write(formatted); err != nil {
		return fmt.Errorf("write generated registry: %w", err)
	}
	return nil
}

func checkSourceDirs(root string) ([]string, error) {
	cfg, err := config.LoadConfig(filepath.Join(root, "substrate.json"))
	if err != nil {
		return nil, fmt.Errorf("load substrate.json: %w", err)
	}
	configPath := filepath.Join(root, "substrate.json")
	if !cfg.Present {
		return nil, fmt.Errorf("substrate.json not found at %s", configPath)
	}
	if len(cfg.Profiles) == 0 {
		return nil, fmt.Errorf("substrate.json has no profiles")
	}

	core := filepath.Join(root, "core", "checks.d")
	info, err := os.Stat(core)
	if err != nil || !info.IsDir() {
		return nil, fmt.Errorf("core checks not found at %s", core)
	}

	dirs := []string{core}
	for _, name := range cfg.Profiles {
		profile, err := resolveProfileDir(root, name)
		if err != nil {
			return nil, err
		}
		dirs = append(dirs, filepath.Join(profile, "checks.d"))
	}
	dirs = append(dirs, filepath.Join(root, "checks.d"))
	return dirs, nil
}

func resolveProfileDir(root, name string) (string, error) {
	for _, dir := range []string{
		filepath.Join(root, "substrate-profiles", name),
		filepath.Join(root, "profiles", name),
	} {
		if info, err := os.Stat(dir); err == nil && info.IsDir() {
			return dir, nil
		}
	}
	return "", fmt.Errorf("unknown profile: %s", name)
}

func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", fmt.Errorf("hash %s: %w", path, err)
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, ".substrate", "VERSION")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf(".substrate/VERSION not found from %s", dir)
		}
		dir = parent
	}
}
