package main

import (
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "generate-registry: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findRoot()
	if err != nil {
		return fmt.Errorf("find repo root: %w", err)
	}

	digests := make(map[string]string)
	var keys []string

	collect := func(dir string) error {
		entries, err := os.ReadDir(dir)
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return fmt.Errorf("read %s: %w", dir, err)
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".sh") {
				continue
			}
			if _, ok := digests[e.Name()]; ok {
				continue
			}
			h, err := sha256File(filepath.Join(dir, e.Name()))
			if err != nil {
				return fmt.Errorf("hash %s: %w", e.Name(), err)
			}
			digests[e.Name()] = h
			keys = append(keys, e.Name())
		}
		return nil
	}

	for _, d := range []string{
		filepath.Join(root, "checks.d"),
		filepath.Join(root, ".substrate", "checks.d"),
	} {
		if err := collect(d); err != nil {
			return err
		}
	}
	sort.Strings(keys)

	w := os.Stdout
	emit := func(s string) error {
		if _, err := fmt.Fprint(w, s); err != nil {
			return fmt.Errorf("write: %w", err)
		}
		return nil
	}
	if err := emit("// Code generated by generate-registry; DO NOT EDIT.\n\n"); err != nil {
		return fmt.Errorf("write header: %w", err)
	}
	if err := emit("package gate\n\n"); err != nil {
		return fmt.Errorf("write package: %w", err)
	}
	if err := emit("var RegistryDigests = map[string]string{\n"); err != nil {
		return fmt.Errorf("write map open: %w", err)
	}
	for _, k := range keys {
		if err := emit(fmt.Sprintf("\t%q: %q,\n", k, digests[k])); err != nil {
			return fmt.Errorf("write entry %s: %w", k, err)
		}
	}
	if err := emit("}\n"); err != nil {
		return fmt.Errorf("write map close: %w", err)
	}
	return nil
}

func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", fmt.Errorf("hash %s: %w", path, err)
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, ".substrate", "VERSION")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf(".substrate/VERSION not found from %s", dir)
		}
		dir = parent
	}
}
