// Code generated by generate-registry; DO NOT EDIT.

package gate

var RegistryDigests = map[string]string{
	"05-unclaimed-source.sh": "475d7a62c46c32f2b73b9c31e8dbe7748ceab3c418c9dc7a98c12803c343f09f",
	"10-comments.sh": "bb87f42e68210d8b42708f1d1d2dff1da9d654f53aa5a520d070bb952be2b5e0",
	"15-tracking.sh": "951fb89c47d24aa9e6528a327783bda81ed4e17487c754b994577ae229f47b84",
	"20-duplication.sh": "fb6487d0bc40c4302007d337781fee989310e39b1027527f6f3aef9c17d426cb",
	"30-budgets.sh": "cc8c09b3a1ff1cf89ee15852ec21f51fa1ffc3a14af89924b19fa870b4bf6f3d",
	"40-data-validity.sh": "aefaca5b882bb0049027e57fe67b1fd7c89380a3e883c1f3f79759f1db94679b",
	"45-contract-drift.sh": "82a0c222b1980d3068c99ac816c1cfb2e65313cb5a990fb695ac9f9e534b9425",
	"50-gitleaks.sh": "bd7374f127abafa2d263ca5b41297289f0a6f8fb2a0ca7bd715a62725e3ef278",
	"59-actionlint.sh": "1b29e1df61495439dda8372886a23b92a512b85688ee76fd6c06d941809a05f2",
	"60-ruff.sh": "67930106c63f018c06d7b9d7beebdafa06961ba2039e8d29d771551e6c0f933a",
	"60-shellcheck.sh": "1528a6b7289ff24eb7a458350058ef425dba40f1cdeeaa574b283b0ccd3b69f0",
	"61-py-syntax.sh": "714eb025baadc808706bb0a48eff5d8812ea1130b897a26ca702dfce3505c4a9",
	"62-import-linter.sh": "f3db39ebfd045d32d955a9ff1576fc23d010b023e458bfe3957c5baffd157e37",
	"63-vulture.sh": "459eeafc76eb9ba194b21b1759210761a0d7d09838e4a1bdadd6afa59b12bb0b",
	"64-constructs.sh": "f3d21af9f2955a9a322592ac1822f4ebfc83602fc59609c6bea0152ae776d2a2",
	"71-kit-tsc.sh": "cabbb616bc9ae844428dcb9e5e792765d7bcf35e419156ebd6e788238e4a0acb",
	"75-go-build.sh": "3b9f0570148fc3c191016319bf6f33289c7f26314fd61c2ba3817319d1ae9eb8",
	"76-golangci.sh": "cc5db7898c660f2abc9d3264a1ffc1b3aec83adbc50bd5e038c647e170b68b57",
	"81-engine-ts-parity.sh": "22a5855b40be4eed552b3a8275208c6a09352412ec06653721bb6e3b529f6f5b",
	"82-check-registry.sh": "400224b0ab565d936666a9b3d18d4228810c3f6d245958ac48edc5dcc92332fa",
}
