// Installed by `substrate init` into <repo>/.omp/extensions/. Mirrors the
// Claude Code hooks: path protection (tool_call) + comment ratchet (tool_result),
// both driven by substrate.json. Regenerated by `substrate update` — do not hand-edit.
import { lstatSync, realpathSync, readFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

const HARD: Array<[RegExp, string]> = [
	[/(^|\/)substrate-baseline\.json$/, "baseline changes only via the gate (--update-baseline)"],
	[/(^|\/)\.substrate(\/|$)/, "vendored substrate core — change the kit and run: substrate update"],
	[/(^|\/)CLAUDE\.md$/, "governance doc — propose the edit to the user instead"],
];

function globToRegExp(glob: string): RegExp {
	let out = "";
	for (let i = 0; i < glob.length; i++) {
		const c = glob[i];
		if (c === "*") {
			if (glob[i + 1] === "*") {
				out += ".*";
				i++;
			} else {
				out += "[^/]*";
			}
		} else if (c === "?") {
			out += "[^/]";
		} else if ("\\^$.|+()[]{}".includes(c)) {
			out += `\\${c}`;
		} else {
			out += c;
		}
	}
	return new RegExp(`^${out}$`);
}

type Config = {
	ok: boolean;
	missing: boolean;
	protectedGlobs: RegExp[];
	contractPaths: string[];
	contractsInvalid: boolean;
};

function loadConfig(cwd: string): Config {
	let raw: string;
	try {
		raw = readFileSync(resolve(cwd, "substrate.json"), "utf8");
	} catch {
		return { ok: true, missing: true, protectedGlobs: [], contractPaths: [], contractsInvalid: false };
	}
	try {
		const cfg = JSON.parse(raw);
		const globs = Array.isArray(cfg.protected_paths) ? cfg.protected_paths : [];
		const contracts = Array.isArray(cfg.contracts) ? cfg.contracts : [];
		const contractsInvalid = contracts.some(
			(c: { name?: unknown; regen?: unknown; paths?: unknown }) =>
				!c || typeof c.name !== "string" || typeof c.regen !== "string" || !Array.isArray(c.paths),
		);
		const contractPaths: string[] = contracts.flatMap((c: { paths?: string[] }) =>
			Array.isArray(c.paths) ? c.paths : [],
		);
		return {
			ok: true,
			missing: false,
			protectedGlobs: globs.map(globToRegExp),
			contractPaths,
			contractsInvalid,
		};
	} catch {
		return { ok: false, missing: false, protectedGlobs: [], contractPaths: [], contractsInvalid: false };
	}
}

function toolPath(input: Record<string, unknown>): string {
	return String(input.path ?? input.file_path ?? "");
}

export default function substrateQuality(pi: ExtensionAPI): void {
	pi.setLabel("Substrate gates");

	pi.on("tool_call", async (event, ctx) => {
		if (event.toolName !== "write" && event.toolName !== "edit") return;
		const path = toolPath(event.input);
		if (!path) return;

		const cfg = loadConfig(ctx.cwd);
		if (!cfg.ok) {
			return { block: true, reason: "blocked: substrate.json is corrupt — fix it before writing anything else" };
		}
		if (cfg.contractsInvalid) {
			return {
				block: true,
				reason: "blocked: substrate.json contracts entries need name/regen/paths — fix the config",
			};
		}

		const abs = resolve(ctx.cwd, path);
		try {
			if (lstatSync(abs).isSymbolicLink()) {
				let target = "unknown";
				try {
					target = realpathSync(abs);
				} catch {}
				return {
					block: true,
					reason: `blocked: ${path} is a symlink to ${target} — writing through it clobbers the target; edit the target explicitly if that is intended`,
				};
			}
		} catch {}

		const rel = relative(ctx.cwd, abs);
		let real = rel;
		try {
			real = relative(ctx.cwd, realpathSync(abs));
		} catch {
			try {
				real = relative(ctx.cwd, join(realpathSync(dirname(abs)), basename(abs)));
			} catch {}
		}
		if (real.startsWith("..") || isAbsolute(real)) {
			return {
				block: true,
				reason: `blocked: ${path} resolves outside the repo (${real}) — a parent directory is a symlink`,
			};
		}

		for (const [re, why] of HARD) {
			if (re.test(rel) || re.test(real)) {
				return { block: true, reason: `blocked: ${rel} — ${why}` };
			}
		}
		for (const re of cfg.protectedGlobs) {
			if (re.test(rel) || re.test(real)) {
				return { block: true, reason: `blocked: ${rel} is protected by substrate.json protected_paths` };
			}
		}
		for (const p of cfg.contractPaths) {
			if (rel === p || rel.startsWith(`${p}/`) || real === p || real.startsWith(`${p}/`)) {
				return {
					block: true,
					reason: `blocked: ${rel} is generated from a contract — edit the contract source; the gate regenerates (substrate.json contracts)`,
				};
			}
		}
	});

	pi.on("tool_result", async (event, ctx) => {
		if (event.toolName !== "write" && event.toolName !== "edit") return;
		if (event.isError) return;
		const path = toolPath(event.input);
		if (!path) return;
		const proc = Bun.spawnSync([".substrate/comment-ratchet.sh", path], {
			cwd: ctx.cwd,
			stdout: "pipe",
			stderr: "pipe",
		});
		if (proc.exitCode === 0) return;
		const report = new TextDecoder().decode(proc.stdout).trim();
		if (!report) return;
		return {
			content: [
				...event.content,
				{ type: "text", text: `\n[comment ratchet — fix before proceeding]\n${report}` },
			],
		};
	});
}
